version: '3'
services:
  transmission:
    image: linuxserver/transmission
    restart: unless-stopped
    volumes:
      - "/mnt/vols/transmission/config:/config"
      - "nfs_downloads:/downloads"
      - "/mnt/vols/transmission/watch:/watch"
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    environment:
      PUID: "${UID}"
      PGID: "${GID}"
      TZ: "Europe/London"
volumes:
  nfs_downloads:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=10.0.2.10,soft,rw"
      device: ":/export/storage/tmp/downloads"
