version: '3'

services:
  hass:
    container_name: hass
    image: homeassistant/home-assistant:stable
    volumes:
      - "/mnt/vols/hass/config:/config"
    environment:
      - TZ=Europe/London
    restart: unless-stopped
    network_mode: host