version: '3'
services:
  calibre:
    image: linuxserver/calibre-web
    container_name: calibre-web
    restart: unless-stopped
    volumes:
      - "/mnt/vols/calibre/config:/config"
      - "/mnt/vols/calibre/library:/books"
    ports:
      - "8083:8083"
    environment:
      PUID: "${UID}"
      PGID: "${GID}"
      TZ: "Europe/London"
      DOCKER_MODS: "linuxserver/calibre-web:calibre"
